release:
  build: .
  environment:
    - AWS_ACCESS_KEY_ID
    - AWS_DEFAULT_REGION
    - AWS_SECRET_ACCESS_KEY
    - CIRCLE_TOKEN
    - DOCKER_EMAIL
    - DOCKER_USERNAME
    - DOCKER_PASSWORD
    - EQUINOX_ACCOUNT
    - EQUINOX_APP
    - EQUINOX_SECRET
    - SLACK_WEBHOOK_URL
  volumes:
    - .:/go/src/github.com/convox/release
    - /var/run/docker.sock:/var/run/docker.sock
